### ISSUE TITLE
Orca's Heart crashed on linux

### ISSUE THREAD

**Issue by docb** [scanner-darkly/vcv-collection-one#10]
b7e7ed7ce690072582a4891e7135b4537bf46fe9 with rack 2.0.4 linux ubuntu jack2
Steps:
add Orca's Heart on an empty patch.
quit
start rack again
==> segmentation fault
gdb says: seg fault in SDOrcasHeart.cpp line 477
observed similar issue already in an other plugin module.
the textDisplay is not allocated if the module is running before the widget is created which seems to happen here.
if i workaround by setting textDisplay to nullptr initially and add a null check in the block starting in 477 all works fine
may be then it seems to be dangerous to allocate something for the module (which is accessed by process)  inside the widget code.

**Comment by FMTolstoevsky** [comment]
Same problems with rack 2.0.4 on windows (at least my old W7) - 
any attempt to open a patch with Orca or even to re-open rack after adding Orca on empty patch and restarting rack immediately causes crash

**Comment by Petervos2018** [comment]
Windows 10 20H2 same as @FMTolstoevsky

**Comment by scanner-darkly** [comment]
@docb @FMTolstoevsky @Petervos2018 thanks for the bug reports!
i believe it should be fixed now, could you give this version a try? https://github.com/scanner-darkly/vcv-collection-one/actions/runs/1623000649

**Comment by docb** [comment]
70a282a76d3a6da7fb84dd45aa1e4670538a951e  the problem is gone, thanks.

**Comment by Petervos2018** [comment]
Looks good on Win 10 👍

**Comment by FMTolstoevsky** [comment]
Just checked - re-opening is Ok on Win7 too. Thanks!

**Comment by scanner-darkly** [comment]
great, thanks for confirming!

**Comment by scanner-darkly** [comment]
fixed in 7f6b993fa7880f1b2aae04e5f3875ae3b84b4de3
