### ISSUE TITLE
Tag v2.0.4

### ISSUE THREAD

**Issue by cbix** [scanner-darkly/vcv-collection-one#11]
Could you please add a git tag/release for the `v2.0.4` stable version? Thanks :)

**Comment by scanner-darkly** [comment]
done! could you tell me more about archlinux-proaudio?

**Comment by cbix** [comment]
Thanks! It's an effort to package open source pro-audio and music applications and plugins for Arch Linux and provide an easy-to-use binary repo. Having proper release tags makes packaging a lot easier, since we can use the package version directly in the source URL ;)

**Comment by scanner-darkly** [comment]
thanks for the explanation, makes sense! where can in find more info about this project, is there a thread somewhere?

**Comment by cbix** [comment]
Mostly on the [website](https://arch.osamc.de/) and the [GitHub repo](https://github.com/osam-cologne/archlinux-proaudio).
