### ISSUE TITLE
minor build issues

### ISSUE THREAD

**Issue by davephillips** [scanner-darkly/vcv-collection-one#2]
VCV Rack v1.dev
Linux Fedora 23

Hi ! I hit a couple of small issues when building your plugin on my old Fedora system:

```
$ make clean
Makefile:22: ../rack-sdk/plugin.mk: No such file or directory
make: *** No rule to make target '../rack-sdk/plugin.mk'.  Stop.
```
Easily fixed by replacing this:

`RACK_DIR ?= ../rack-sdk`

with this:

`RACK_DIR ?= ../..`

Next issue:

```
$ make dist
g++  -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=athlon-fx -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/SDOrcasHeart.cpp.o src/SDOrcasHeart.cpp
src/SDOrcasHeart.cpp:184:27: error: array must be initialized with a brace-enclosed initializer
     int scales[SCALECOUNT][SCALELEN] = {0};
                           ^
../../compile.mk:61: recipe for target 'build/src/SDOrcasHeart.cpp.o' failed
make: *** [build/src/SDOrcasHeart.cpp.o] Error 1
```
Older versions of GCC require that this:

`int scales[SCALECOUNT][SCALELEN] = {0};`

be replaced by this:

`int scales[SCALECOUNT][SCALELEN] = {{0}};`

Your plugin then builds cleanly and without complaint from my compiler. It loads fine in VCV Rack, I look forward to playing with it today. Thank you for your work ! :)

**Comment by scanner-darkly** [comment]
this is super helpful - thank you!

**Comment by scanner-darkly** [comment]
fixed in https://github.com/scanner-darkly/vcv-collection-one/commit/76b610656584ed0fc3a60aeed8ae3fd77ab87359
@davephillips could you give this a try?

**Comment by davephillips** [comment]
All good now. Thanks for the great module !
