### ISSUE TITLE
Missing diagram on Orca's Heart wiki page

### ISSUE THREAD

**Issue by jimallman** [scanner-darkly/vcv-collection-one#5]
Looks like the URL for this image should be updated to
https://raw.githubusercontent.com/scanner-darkly/vcv-collection-one/main/doc/oh_diagram.jpg

Apologies, I'd make a tiny pull request instead, but it's not clear how to fork the wiki "sub-repo".

**Comment by scanner-darkly** [comment]
thank you, fixed!
(there is a way to clone the wiki as a repo but you have to manually adjust the git link iirc)
